feat: реализован сервис статистики
VPerevozchikov/java-explore-with-me pull request #3
Opened 2023-08-27 10:00 UTC by VPerevozchikov

2023-08-27 20:41 UTC, db-exp requested changes

2023-08-27 20:41 UTC, db-exp commented on stat_svc/DTO/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +public class EndpointHitDto {
для NotBlank можно сразу прописывать Size

2023-08-27 20:41 UTC, db-exp commented on stat_svc/Server/src/main/resources/schema.sql
> +     ip VARCHAR(255) NOT NULL,
очень много) 40

2023-08-27 20:41 UTC, db-exp commented on stat_svc/Server/src/main/resources/schema.sql
> +     app VARCHAR(255) NOT NULL,
много - можно 100 поставить

2023-08-27 20:41 UTC, db-exp commented on stat_svc/Client/src/main/java/ru/practicum/client/StatsClient.java
> +        RestTemplateBuilder builder = new RestTemplateBuilder();
лучше RestTemplate получать как бин сюда (можно определить свой в конфигурации), а сам клиент сделать сервисом

2023-08-27 20:41 UTC, db-exp commented on stat_svc/Client/src/main/java/ru/practicum/client/StatsClient.java
> +        String serverUrl = "http://ewm-stat-server:9090";
лучше получить из application.properties в конструкторе

2023-09-01 03:10 UTC, VPerevozchikov commented on stat_svc/DTO/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +public class EndpointHitDto {
выполнено

2023-09-01 03:10 UTC, VPerevozchikov commented on stat_svc/Server/src/main/resources/schema.sql
> +     ip VARCHAR(255) NOT NULL,
исправил

2023-09-01 03:10 UTC, VPerevozchikov commented on stat_svc/Server/src/main/resources/schema.sql
> +     app VARCHAR(255) NOT NULL,
исправил

2023-09-01 03:11 UTC, VPerevozchikov commented on stat_svc/Client/src/main/java/ru/practicum/client/StatsClient.java
> +        RestTemplateBuilder builder = new RestTemplateBuilder();
готово

2023-09-01 03:11 UTC, VPerevozchikov commented on stat_svc/Client/src/main/java/ru/practicum/client/StatsClient.java
> +        String serverUrl = "http://ewm-stat-server:9090";
исправил

2023-09-01 14:46 UTC, db-exp approved these changes

2023-09-01 20:19 UTC, merged